fragment ScenarioContent on Scenario {
  id
  name
  paymentType
  imgUrl
  currency
  notes
  dueDateDays
  createdAt
  updatedAt
  clientId
  merchantId
}

mutation createScenario($data: ScenarioCreateInput!) {
  createdScenario: createOneScenario(data: $data) {
    ...ScenarioContent
  }
}

query scenarioList {
  scenarioList: scenarios {
    id
    imgUrl
  }
}

query scenario($where: ScenarioWhereUniqueInput!) {
  scenario(where: $where) {
    ...ScenarioContent
    merchant {
      ...MerchantContent
    }
    client {
      ...ClientContent
    }
  }
}
