fragment Scenario on scenarios {
  id
  name
  paymentType
  imgUrl
  currency
  notes
  dueDateDays
  createdAt
  updatedAt
  merchantId
  clientId
}

mutation createScenario($object: scenarios_insert_input!) {
  insert_scenarios_one(object: $object) {
    ...Scenario
  }
}

mutation createInvoice($object: invoices_insert_input!) {
  insert_invoices_one(object: $object) {
    id
  }
}

query scenarioList($limit: Int = 10, $offset: Int = 0) {
  scenarios(limit: $limit, offset: $offset) {
    id
    imgUrl
    name
  }
}

query scenario($id: Int_comparison_exp!) {
  scenarios(where: { id: $id }) {
    ...Scenario
    client {
      ...Client
    }
    merchant {
      ...Merchant
    }
  }
}
