fragment ScenarioContent on Scenario {
  id
  name
  paymentType
  imgUrl
  netPerOne
  VAT
  unitType
  currency
  notes
  dueDateDays
  createdAt
  updatedAt
  clientId
  merchantId
}

mutation createScenario($data: ScenarioCreateInput!) {
  createdScenario: createOneScenario(data: $data) {
    ...ScenarioContent
  }
}
