fragment Scenario on scenarios {
  id
  name
  paymentType: payment_type
  imgUrl: img_url
  currency
  notes
  dueDateDays: due_date_days
  createdAt: created_at
  updatedAt: updated_at
  merchantId: merchant_id
  clientId: client_id
}

mutation createScenario($object: scenarios_insert_input!) {
  insert_scenarios_one(object: $object) {
    ...Scenario
  }
}

mutation createInvoice($object: invoices_insert_input!) {
  insert_invoices_one(object: $object) {
    id
  }
}

query scenarioList($limit: Int = 10, $offset: Int = 0) {
  scenarios(limit: $limit, offset: $offset) {
    id
    imgUrl: img_url
    name
  }
}

query scenario($id: Int_comparison_exp!) {
  scenarios(where: { id: $id }) {
    ...Scenario
    client {
      ...Client
    }
    merchant {
      ...Merchant
    }
  }
}
