fragment Scenario on Scenario {
  id
  name
  paymentType
  imgUrl
  currency
  notes
  dueDateDays
  createdAt
  updatedAt
  merchantId
  clientId
}

mutation createScenario($object: Scenario_insert_input!) {
  insert_Scenario_one(object: $object) {
    ...Scenario
  }
}

mutation createInvoice($object: Invoice_insert_input!) {
  insert_Invoice_one(object: $object) {
    id
  }
}

query scenarioList($limit: Int = 10, $offset: Int = 0) {
  Scenario(limit: $limit, offset: $offset) {
    id
    imgUrl
    name
  }
}

query scenario($id: Int_comparison_exp = {}) {
  Scenario(where: { id: $id }) {
    ...Scenario
    Client {
      ...Client
    }
    Merchant {
      ...Merchant
    }
  }
}
