fragment Invoice on Invoice {
  id
  invoiceNumber
  issueDate
  updatedAt
  items {
    price
    quantity
  }
  Scenario {
    currency
    Client {
      name
    }
    Merchant {
      companyName
    }
  }
}

query invoice($id: Int_comparison_exp!) {
  Invoice(where: { id: $id }) {
    issueDate
    invoiceNumber
    items {
      name
      price
      quantity
    }
  }
}

mutation updateInvoice($id: Int_comparison_exp!, $_set: Invoice_set_input!) {
  update_Invoice(where: { id: $id }, _set: $_set) {
    returning {
      ...Invoice
      Scenario {
        id
        name
      }
    }
  }
}

mutation deleteInvoice($id: Int_comparison_exp!) {
  delete_Invoice(where: { id: $id }) {
    returning {
      id
    }
  }
}

query invoiceList(
  $limit: Int = 10
  $offset: Int = 0
  $order_by: [Invoice_order_by!] = {}
  $where: Invoice_bool_exp = {}
) {
  Invoice(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    ...Invoice
  }
  Invoice_aggregate {
    aggregate {
      totalCount: count
    }
  }
}
