fragment InvoicePaginatedListItemContent on Invoice {
  id
  invoiceNumber
  issueDate
  updatedAt
  items {
    price
    quantity
  }
  scenario {
    currency
    # client {
    # name
    # }
    merchant {
      companyName
    }
  }
}

query invoice($id: Int) {
  invoice(where: { id: $id }) {
    issueDate
    invoiceNumber
    items {
      name
      price
      quantity
    }
  }
}
query paginatedInvoiceList(
  $orderBy: [InvoiceOrderByWithRelationInput!] = []
  $where: InvoiceWhereInput
  $skip: Int!
  $take: Int = 10
) {
  invoiceList: invoices(orderBy: $orderBy, where: $where, skip: $skip, take: $take) {
    ...InvoicePaginatedListItemContent
  }
  totalCount: totalInvoicesCount
  filters: invoiceFilters {
    scenario {
      id
      name
    }
  }
}

mutation updateInvoice($data: InvoiceUpdateInput!, $id: Int!) {
  updatedInvoice: updateOneInvoice(data: $data, where: { id: $id }) {
    ...InvoicePaginatedListItemContent
    scenario {
      id
      name
    }
  }
}

mutation deleteInvoice($id: Int!) {
  deletedInvoice: deleteOneInvoice(where: { id: $id }) {
    id
  }
}
