fragment Invoice on invoices {
  id
  invoiceNumber: invoice_number
  issueDate: issue_date
  updatedAt: updated_at
  items {
    price
    quantity
    id
  }
  scenario {
    currency
    client {
      name
    }
    merchant {
      companyName: company_name
    }
  }
}

query invoice($id: Int_comparison_exp!) {
  invoices(where: { id: $id }) {
    issueDate: issue_date
    invoiceNumber: invoice_number
    items {
      name
      price
      quantity
    }
  }
}

mutation updateInvoice($id: Int_comparison_exp!, $_set: invoices_set_input!) {
  update_invoices(where: { id: $id }, _set: $_set) {
    returning {
      ...Invoice
      scenario {
        id
        name
      }
    }
  }
}

mutation deleteInvoice($id: Int_comparison_exp!) {
  delete_invoices(where: { id: $id }) {
    returning {
      id
    }
  }
}

query invoiceList(
  $limit: Int = 10
  $offset: Int = 0
  $order_by: [invoices_order_by!] = {}
  $where: invoices_bool_exp = {}
) {
  invoices(limit: $limit, offset: $offset, order_by: $order_by, where: $where) {
    ...Invoice
  }
  invoices_aggregate {
    aggregate {
      totalCount: count
    }
  }
}
