SET check_function_bodies = false;
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (1, 'Motimate', 'Karvesvingen 1', '0579', 'Oslo', 'Norway', '917 385 947');
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (3, 'Michael Stefan Konczak', 'os Stefana Batorego 39 12', '60-687', 'Poznan', 'Poland', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (45, 'Braciszek', 'AkkreBrygge', '121', 'Oslo', 'Norway', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (46, 'Test', 'os Stefana Batorego 39 12', '60-687', 'Poznan', 'Poland', '1223231');
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (47, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (48, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (49, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (50, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (51, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (52, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (53, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (54, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (55, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (56, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (57, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (58, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (59, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (60, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (61, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (62, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (63, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (64, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (65, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (66, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (67, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (68, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (69, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (70, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (1, 'Michal Konczak', 'Michal Konczak', 'os Stefana Batorego 39/12', '60-687', 'Poznan', 'Poland', 'michal.stefan.konczak@gmail.com', 'mBank', '07 1140 2004 0000 3702 8136 6339', '24 1140 2004 0000 3012 1306 9515', '9721317499');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (2, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (3, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (4, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (5, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (6, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (7, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (8, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (9, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (10, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (11, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (12, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (13, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (14, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (15, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (16, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (17, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (18, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (19, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (20, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (21, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (22, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (23, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.merchants (id, "issuerName", "companyName", address, "postCode", city, country, email, "bankName", "bankAccountPln", "bankAccountEur", "vatId") VALUES (24, 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', '');
INSERT INTO public.scenarios (id, name, "imgUrl", notes, "dueDateDays", "paymentType", currency, "createdAt", "updatedAt", "clientId", "merchantId") VALUES (1, 'Motimate', 'https://play-lh.googleusercontent.com/DN6JNgjHvMgO_HKeFpxBsKMFHI8kdHodiv-FPP-ro5uxb26Ao1TLPZw7zEma_VgWLm0', '', 5, 'TRANSFER', 'EUR', '2021-11-20 16:50:38.524', '2021-11-20 16:50:38.524', 1, 1);
INSERT INTO public.scenarios (id, name, "imgUrl", notes, "dueDateDays", "paymentType", currency, "createdAt", "updatedAt", "clientId", "merchantId") VALUES (2, 'testwo', 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260', '', 10, 'TRANSFER', 'EUR', '2021-11-21 18:30:49.538', '2021-11-21 18:30:49.538', 1, 1);
INSERT INTO public.invoices (id, "invoiceNumber", "issueDate", "createdAt", "updatedAt", "scenarioId") VALUES (4, '02/11/2021', '20/11/2021', '2021-11-21 14:07:22.25', '2021-11-21 18:32:19.145', 1);
INSERT INTO public.invoice_items (id, name, quantity, price, vat, "createdAt", "updatedAt", "invoiceId") VALUES (2, 'Services', 176, 32, 'DOES_NOT_CONCERN', '2021-11-21 14:07:22.25', '2021-11-21 14:07:22.25', 4);
INSERT INTO public.invoice_items (id, name, quantity, price, vat, "createdAt", "updatedAt", "invoiceId") VALUES (3, 'Costs related to travel', 1, 700, 'PERCENT_8', '2021-11-21 14:07:22.25', '2021-11-21 14:07:22.25', 4);
SELECT pg_catalog.setval('public."Client_id_seq"', 70, true);
SELECT pg_catalog.setval('public."InvoiceItem_id_seq"', 3, true);
SELECT pg_catalog.setval('public."Invoice_id_seq"', 4, true);
SELECT pg_catalog.setval('public."Merchant_id_seq"', 24, true);
SELECT pg_catalog.setval('public."Scenario_id_seq"', 3, true);
