SET check_function_bodies = false;
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (1, 'Motimate', 'Karvesvingen 1', '0579', 'Oslo', 'Norway', '917 385 947');
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (3, 'Michael Stefan Konczak', 'os Stefana Batorego 39 12', '60-687', 'Poznan', 'Poland', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (45, 'Braciszek', 'AkkreBrygge', '121', 'Oslo', 'Norway', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (46, 'Test', 'os Stefana Batorego 39 12', '60-687', 'Poznan', 'Poland', '1223231');
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (47, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (48, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (49, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (50, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (51, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (52, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (53, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (54, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (55, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (56, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (57, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (58, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (59, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (60, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (61, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (62, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (63, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (64, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (65, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (66, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (67, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (68, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (69, 'text', 'text', 'text', 'text', 'text', NULL);
INSERT INTO public.clients (id, name, address, "postCode", city, country, "vatId") VALUES (70, 'text', 'text', 'text', 'text', 'text', NULL);
SELECT pg_catalog.setval('public."Client_id_seq"', 70, true);
